分页期、Select、button调整
yuxuan/osui pull request #18
Opened 2023-04-14 11:23 UTC by BrotaOne

分页期、Select、button调整（主要是sm样式调整）
BrandProvider 支持透传ConfigProvider参数（便于datePicker传递locale等）

2023-04-14 11:45 UTC, yuxuan commented on packages/ui/brand-provider/src/index.tsx
> +    otherConfigProviderProps?: ConfigProviderProps;
这个可以直接交configProviderProps，不用叫other

2023-04-14 11:46 UTC, yuxuan commented on packages/ui/brand-provider/src/themeComponents.ts
> +    }
这些component token是都要单独定义覆盖么？theme token不可以么？

2023-04-14 11:47 UTC, yuxuan commented on packages/ui/button/src/index.less
> +.ant-btn.ant-btn-sm {
.ant 开头的需要用 .${ant-prefix} 为了能支持有的产品改了 ant 的前缀

2023-04-14 11:47 UTC, yuxuan commented on packages/ui/modal/src/index.less
> +            .ant-modal-close-x {
这里也是

2023-04-14 11:47 UTC, yuxuan commented on packages/ui/modal/src/index.less
> +        .ant-modal-close-x {
这里也是

2023-04-14 11:51 UTC, yuxuan commented on packages/ui/pagination/src/index.tsx
> +    if (uiType === 'antd'){
这个我又想了想，先不加对antd原来使用方式的支持了，osui的就是osui的吧

2023-04-14 11:54 UTC, yuxuan commented on packages/ui/select/src/index.less
> +.ant-select-multiple  {
这几个也是

2023-04-14 11:54 UTC, yuxuan commented on packages/ui/steps/src/index.less
> +.ant-steps-label-vertical:not(.ant-steps-dot) .ant-steps-item-container .ant-steps-item-tail {
这几个也是

2023-04-14 11:55 UTC, yuxuan requested changes, later dismissed
我们还是得把rc-pagination拿过来么？

2023-04-19 06:47 UTC, BrotaOne commented on packages/ui/brand-provider/src/themeComponents.ts
> +    }
这里面大部分应该是不能的，可以在全部处理完之后，看看有没有统一的，现在有的是已经和 theme token 不一样的设置，有些组件的 token 就是不一样的
![image](https://user-images.githubusercontent.com/30154715/232989426-4618c645-a036-4e90-a0a4-97cd6e1c5f60.png)
![image](https://user-images.githubusercontent.com/30154715/232989502-a037c903-5ff6-46bc-9b76-4e8c3b66fd95.png)

2023-04-27 07:09 UTC, merged